package Yal2Jvm;

import Yal2Jvm.CodeGeneration.IR.*;
import Yal2Jvm.CodeGeneration.IRFilling.AssignIRFiller;
import Yal2Jvm.SemanticAnalysis.InitializationVerifier.AssignInitializationVerifier;
import Yal2Jvm.SemanticAnalysis.STFilling.AssignSTFiller;

import java.util.HashSet;

/* Generated By:JJTree: Do not edit this line. Yal2Jvm.ASTAssign.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/**
 * Assign expression generated by JJTree.
 * ASTAssign overrides the dump, fillStSecondPass, fillIRSecondPass and verifyInitialization methods from the SimpleNode class so it can introduce special behaviors for each.
 */
public class ASTAssign extends SimpleNode
{
    /**
     * Is responsible for filling the symbol table.
     */
    private final AssignSTFiller assignSTFiller = new AssignSTFiller(this);
    /**
     * Is responsible for verifying the initialization of variables.
     */
    private final AssignInitializationVerifier assignInitializationVerifier = new AssignInitializationVerifier(this);
    /**
     * Is responsible for filling the IR.
     */
    private final AssignIRFiller assignIRFiller = new AssignIRFiller(this);

    /**
     * Constructor of the non-terminal expression 'Assign'.
     * @param id ID of the node.
     */
    public ASTAssign(int id)
    {
        super(id);
    }
    /**
     * Constructor of the non-terminal expression 'Assign'.
     * @param p Scanner object.
     * @param id ID of the node.
     */
    public ASTAssign(Scanner p, int id)
    {
        super(p, id);
    }

    /**
     * This method is called recursively to go through the entire AST to fill the symbol table.
     * It is Overridden by this derived classes because special behaviour is needed. That special behaviour is implemented by the function fillStSecondPass on the class AssignSTFiller.
     * It is placed in the AST because it needs to go through it. The code to perform the actual filling and necessary semantic analysis is placed in different classes, respecting the single responsibility principle.
     * On the second pass, function bodies are filled in the symbol table.
     * @param st An Object that represents the symbol table to be filled.
     */
    @Override
    public void fillStSecondPass(ST st)
    {
        assignSTFiller.fillStSecondPass(st);
    }

    /**
     * This method is called recursively to go through the entire AST verify the variable initialization.
     * It is Overridden by this derived classes because special behaviour is needed. That special behaviour is implemented by the function verifyInitialization on the class AssignInitializationVerifier.
     * It is placed in the AST because it needs to go through it. The code to perform the actual verification of the variable initialization is placed in different classes, respecting the single responsibility principle.
     * @param initializedVariables A set containing the currently initialized variables (in the current node of the AST). As new variables get initialized, they are added to the set.
     * @param st An Object that represents the already filled symbol table.
     * @return The set of initialized variables after the current AST node (new variables could eventually have been added to the set it received as parameter if they actually for initialized in the current AST node).
     */
    public HashSet verifyInitialization(HashSet<String> initializedVariables, ST st)
    {
        return assignInitializationVerifier.verifyInitialization(initializedVariables, st);
    }

    /**
     * This method is called recursively to go through the entire AST to fill the intermediate representation (IR).
     * It is Overridden by this derived classes because special behaviour is needed. That special behaviour is implemented by the function fillIRSecondPass on the class AssignIRFiller.
     * It is placed in the AST because it needs to go through it. The code to perform the actual filling is placed in different classes, respecting the single responsibility principle.
     * On the first pass, only function definitions are filled in the intermediate representation. Function bodies will be filled in the second pass.
     * @param st An Object that represents the already filled symbol table.
     * @param irContainer A class representing the intermediate representation to be filled.
     * @param currentBlock A class representing the current block on the IR of this AST node. This is used to perform branching on certain conditions.
     */
    public void fillIRSecondPass(ST st, IRContainer irContainer, BasicBlock currentBlock)
    {
        assignIRFiller.fillIRSecondPass(st, irContainer, currentBlock);
    }
}
/*
 * JavaCC - OriginalChecksum=e931d182c52b5c319fcce9e6133dbf59 (do not edit this
 * line)
 */
