package Yal2Jvm;

/* Generated By:JJTree: Do not edit this line. Yal2Jvm.ASTCallErrorHandler.java Version 4.3 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

/**
 * ASTCallErrorHandler generated by JJTree.
 * ASTCallErrorHandler inherits all methods from SimpleNode and doesn't override any.
 */
public class ASTCallErrorHandler extends SimpleNode
{
	/**
	 * Constructor of the ASTCallErrorHandler.
	 * @param id ID of the node.
	 */
    public ASTCallErrorHandler(int id)
    {
        super(id);
    }
    /**
	 * Constructor of the ASTCallErrorHandler.
     * @param p Scanner object.
     * @param id ID of the node.
     */
    public ASTCallErrorHandler(Scanner p, int id)
    {
        super(p, id);
    }

}
/*
 * JavaCC - OriginalChecksum=ca14cc52441ce6f86c8d95602b72a57f (do not edit this
 * line)
 */
