package Yal2Jvm;

/* Generated By:JJTree: Do not edit this line. Yal2Jvm.ASTErrorBlock.java Version 4.3 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/**
 * ASTErrorBlock generated by JJTree.
 * ASTErrorBlock inherits all methods from SimpleNode and doesn't override any.
 */
public class ASTErrorBlock extends SimpleNode
{
	/**
	 * Constructor of the ASTErrorBlock.
	 * @param id ID of the node.
	 */
    public ASTErrorBlock(int id)
    {
        super(id);
    }
    /**
     * Constructor of the ASTErrorBlock.
     * @param p Scanner object.
     * @param id ID of the node.
     */
    public ASTErrorBlock(Scanner p, int id)
    {
        super(p, id);
    }

}
/*\
 * JavaCC - OriginalChecksum=8ce570971546a42ebbc44565adf7d091 (do not edit this
 * line)
 */
