package Yal2Jvm;

import Yal2Jvm.CodeGeneration.IR.*;
import Yal2Jvm.CodeGeneration.IRFilling.IfIRFiller;
import Yal2Jvm.SemanticAnalysis.InitializationVerifier.IfInitializationVerifier;

import java.util.HashSet;

/* Generated By:JJTree: Do not edit this line. Yal2Jvm.ASTIf.java Version 4.3 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/**
 * If expression generated by JJTree.
 * ASTIf overrides the dump, fillIRSecondPass and verifyInitialization methods from the SimpleNode class so it can introduce special behaviors for each.  
 */
public class ASTIf extends SimpleNode {

    /**
     * Is responsible for verifying the initizialition of variables.
     */
    private final IfInitializationVerifier ifInitializationVerifier = new IfInitializationVerifier(this);
    /**
     * Is responsible for filling the IR.
     */
    private final IfIRFiller ifIRFiller = new IfIRFiller(this);

    /**
     * Constructor of the non-terminal expression 'If'.
     * @param id ID of the node.
     */
    public ASTIf(int id) {
        super(id);
    }

    /**
     * Constructor of the non-terminal expression 'If'.
     * @param p Scanner object.
     * @param id ID of the node.
     */
    public ASTIf(Scanner p, int id) {
        super(p, id);
    }

    /**
     * Displays information about this node. Correctly formats the information for more user-friendly reading on the console.
     * The method is overridden in the derived classes whenever special behaviour is necessary.
     * @param prefix The prefix (one or more spaces) to correctly format the information.
     */
    public void dump(String prefix) {
        System.out.println(toString(prefix));
        if (children != null) {
            for (int i = 0; i < children.length; ++i) {
                SimpleNode n = (SimpleNode) children[i];
                if (n != null) {
                    n.dump(prefix + " ");
                }
            }
        }
    }

    /**
     * This method is called recursively to go through the entire AST verify the variable initialization.
     * It is Overridden by this derived classes because special behaviour is needed. That special behaviour is implemented by the function verifyInitialization on the class IfInitializationVerifier.
     * It is placed in the AST because it needs to go through it. The code to perform the actual verification of the variable initialization is placed in different classes, respecting the single responsibility principle.
     * @param initializedVariables A set containing the currently initialized variables (in the current node of the AST). As new variables get initialized, they are added to the set.
     * @param st An Object that represents the already filled symbol table.
     * @return The set of initialized variables after the current AST node (new variables could eventually have been added to the set it received as parameter if they actually for initialized in the current AST node).
     */
    public HashSet verifyInitialization(HashSet<String> initializedVariables, ST st)
    {
        return ifInitializationVerifier.verifyInitialization(initializedVariables, st);
    }

    /**
     * This method is called recursively to go through the entire AST to fill the intermediate representation (IR).
     * It is Overridden by this derived classes because special behaviour is needed. That special behaviour is implemented by the function fillIRSecondPass on the class IfIRFiller.
     * It is placed in the AST because it needs to go through it. The code to perform the actual filling is placed in different classes, respecting the single responsibility principle.
     * On the first pass, only function definitions are filled in the intermediate representation. Function bodies will be filled in the second pass.
     * @param st An Object that represents the already filled symbol table.
     * @param irContainer A class representing the intermediate representation to be filled.
     * @param currentBlock A class representing the current block on the IR of this AST node. This is used to perform branching on certain conditions.
     */
    public void fillIRSecondPass(ST st, IRContainer irContainer, BasicBlock currentBlock)
    {
        ifIRFiller.fillIRSecondPass(st, irContainer, currentBlock);
    }
}
/*
 * JavaCC - OriginalChecksum=5f75d3dd1c027b3050953bb30507da19 (do not edit this
 * line)
 */
