package Yal2Jvm;

/* Generated By:JJTree: Do not edit this line. Yal2Jvm.ASTLhs.java Version 4.3 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/**
 * Lhs expression generated by JJTree.
 * ASTLhs inherits all methods from SimpleNode and doesn't override any.
 */
public class ASTLhs extends SimpleNode
{
	/**
	 * Constructor of the non-terminal expression 'Lhs'.
	 * @param id ID of the node.
	 */
    public ASTLhs(int id)
    {
        super(id);
    }
    /**
     * Constructor of the non-terminal expression 'Lhs'.
     * @param p Scanner object.
     * @param id ID of the node.
     */
    public ASTLhs(Scanner p, int id)
    {
        super(p, id);
    }

}
/*
 * JavaCC - OriginalChecksum=30d586da8c6650fb063b1c8a4ebb16cf (do not edit this
 * line)
 */
