package Yal2Jvm;

/* Generated By:JJTree: Do not edit this line. Yal2Jvm.ASTStmt.java Version 4.3 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/**
 * Stmt expression generated by JJTree.
 * ASTStmt inherits all methods from SimpleNode and doesn't override any.
 */
public class ASTStmt extends SimpleNode
{
	/**
	 * Constructor of the non-terminal expression 'Stmt'.
	 * @param id ID of the node.
	 */
    public ASTStmt(int id)
    {
        super(id);
    }
    /**
     * Constructor of the non-terminal expression 'Stmt'.
     * @param p Scanner object.
     * @param id ID of the node.
     */
    public ASTStmt(Scanner p, int id)
    {
        super(p, id);
    }


}
/*
 * JavaCC - OriginalChecksum=ac78fa7818f732efa94e79d78daad183 (do not edit this
 * line)
 */
