package Yal2Jvm;

/* Generated By:JavaCC: Do not edit this line. ScannerTreeConstants.java Version 6.0_1 */
public interface ScannerTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTDECLARATION = 1;
  public int JJTFUNCTION = 2;
  public int JJTVARLIST = 3;
  public int JJTARRAYELEMENT = 4;
  public int JJTSCALARELEMENT = 5;
  public int JJTSTMTLST = 6;
  public int JJTSTMT = 7;
  public int JJTERRORBLOCK = 8;
  public int JJTASSIGN = 9;
  public int JJTLHS = 10;
  public int JJTRHS = 11;
  public int JJTARRAYSIZE = 12;
  public int JJTTERM = 13;
  public int JJTEXPRTEST = 14;
  public int JJTWHILE = 15;
  public int JJTIF = 16;
  public int JJTCALL = 17;
  public int JJTARGUMENTLIST = 18;
  public int JJTARGUMENT = 19;
  public int JJTARRAYACCESS = 20;
  public int JJTSCALARACCESS = 21;
  public int JJTINDEX = 22;


  public String[] jjtNodeName = {
    "Module",
    "Declaration",
    "Function",
    "Varlist",
    "ArrayElement",
    "ScalarElement",
    "Stmtlst",
    "Stmt",
    "ErrorBlock",
    "Assign",
    "Lhs",
    "Rhs",
    "ArraySize",
    "Term",
    "Exprtest",
    "While",
    "If",
    "Call",
    "ArgumentList",
    "Argument",
    "ArrayAccess",
    "ScalarAccess",
    "Index",
  };
}
/* JavaCC - OriginalChecksum=3c6edcf3bc07f8437d7054f01d23bcce (do not edit this line) */
