@echo off
java -jar Scanner.jar -o all.yal
java -jar Scanner.jar -o array1.yal
java -jar Scanner.jar -o array2.yal
java -jar Scanner.jar -o arraytest.yal
java -jar Scanner.jar -o aval1.yal
java -jar Scanner.jar -o aval3.yal
java -jar Scanner.jar -o aval5.yal
java -jar Scanner.jar -o aval6.yal
java -jar Scanner.jar -o aval7.yal
java -jar Scanner.jar -o aval8.yal
java -jar Scanner.jar -o call-main.yal
java -jar Scanner.jar -o constant-ranges.yal
java -jar Scanner.jar -o input-as-output.yal
java -jar Scanner.jar -o library1.yal
java -jar Scanner.jar -o lsp.yal
java -jar Scanner.jar -o max.yal
java -jar Scanner.jar -o max1.yal
java -jar Scanner.jar -o maxmin.yal
java -jar Scanner.jar -o max_array.yal
java -jar Scanner.jar -o miniArithTest.yal
java -jar Scanner.jar -o nested-branch.yal
java -jar Scanner.jar -o programa1.yal
java -jar Scanner.jar -o programa2.yal
java -jar Scanner.jar -o programa3.yal
java -jar Scanner.jar -o register-test.yal
java -jar Scanner.jar -o sqrt.yal
java -jar Scanner.jar -o stack-size.yal
java -jar Scanner.jar -o testModule1.yal